[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo"

[context.production]
  [context.production.environment]
    HUGO_VERSION = "0.42"
    HUGO_BASEURL = "https://hugo-bare-min.netlify.com/"
